name: Deplayment Artifact
on: push

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test code
              run: npm run test
            - name: Build code
              run: npm build
            - name: Deplay artifact
              run: echo "Deploying artifact"